name: AccuKnox IaC Scan Workflow
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Run IaC scan
        uses: accuknox/iac-scan-action@v0.0.1
        with:
          directory: .
          compact: true
          quiet: true
          output_format: json
          output_file_path: results.json
          framework: Terraform
          soft_fail: true
          endpoint: cspm.demo.accuknox.com
          baseline: baseline
          token: ${{ secrets.TOKEN }}
          tenant_id: ${{ secrets.TENANT_ID }}
          label: ${{ secrets.LABEL }}
